name: publish # TODO: have this use the build workflow
on:
  release:
    types: [created]
jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org' # Can I bake this into package.json?
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm publish # TODO: update the package json with the tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}